# Generated by Django 5.2.4 on 2025-07-03 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('web', 'تصميم وبرمجة المواقع'), ('apps', 'تصميم وبرمجة المتاجر والتطبيقات'), ('hosting', 'استضافة المواقع والتسويق الإلكتروني')], max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('name_ar', models.CharField(max_length=200, null=True)),
                ('name_en', models.CharField(max_length=200, null=True)),
                ('features', models.TextField()),
                ('features_ar', models.TextField(null=True)),
                ('features_en', models.TextField(null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('title_ar', models.CharField(max_length=200, null=True)),
                ('title_en', models.CharField(max_length=200, null=True)),
                ('description', models.TextField()),
                ('description_ar', models.TextField(null=True)),
                ('description_en', models.TextField(null=True)),
                ('icon', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
