# Generated by Django 5.2.4 on 2025-07-03 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_title', models.CharField(max_length=200)),
                ('about_title_ar', models.CharField(max_length=200, null=True)),
                ('about_title_en', models.CharField(max_length=200, null=True)),
                ('about_description', models.TextField()),
                ('about_description_ar', models.TextField(null=True)),
                ('about_description_en', models.TextField(null=True)),
                ('address', models.CharField(max_length=255)),
                ('address_ar', models.CharField(max_length=255, null=True)),
                ('address_en', models.CharField(max_length=255, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=50)),
                ('footer_text', models.CharField(max_length=255)),
                ('footer_text_ar', models.CharField(max_length=255, null=True)),
                ('footer_text_en', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
