# Generated by Django 5.2.4 on 2025-07-05 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_footersection_maincategory_sitedescription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistic',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional image for the statistic', null=True, upload_to='statistics/'),
        ),
    ]
