# Generated by Django 5.2.4 on 2025-07-05 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_statistic_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statistic',
            name='label',
        ),
        migrations.AddField(
            model_name='statistic',
            name='label_ar',
            field=models.CharField(default='Temporary Title', max_length=100, verbose_name='العنوان بالعربية'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistic',
            name='label_en',
            field=models.CharField(default='Temporary Title', max_length=100, verbose_name='العنوان بالإنجليزية'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='statistic',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='statistics/'),
        ),
    ]
