# Generated by Django 5.2.4 on 2025-07-06 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_remove_statistic_label_statistic_label_ar_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='about/')),
                ('company_name', models.CharField(max_length=255)),
                ('heading_ar', models.CharField(max_length=255)),
                ('heading_en', models.CharField(max_length=255)),
                ('description_ar', models.TextField()),
                ('description_en', models.TextField()),
                ('vision_title_ar', models.CharField(max_length=255)),
                ('vision_title_en', models.CharField(max_length=255)),
                ('vision_desc_ar', models.TextField()),
                ('vision_desc_en', models.TextField()),
                ('mission_title_ar', models.CharField(max_length=255)),
                ('mission_title_en', models.CharField(max_length=255)),
                ('mission_desc_ar', models.TextField()),
                ('mission_desc_en', models.TextField()),
                ('goals_title_ar', models.CharField(max_length=255)),
                ('goals_title_en', models.CharField(max_length=255)),
                ('goals_list_ar', models.TextField(help_text='افصل كل هدف بسطر جديد')),
                ('goals_list_en', models.TextField(help_text='Separate each goal with a new line')),
                ('why_us_title_ar', models.CharField(max_length=255)),
                ('why_us_title_en', models.CharField(max_length=255)),
                ('why_us_desc_ar', models.TextField()),
                ('why_us_desc_en', models.TextField()),
                ('techs_title_ar', models.CharField(default='التقنيات التي نعمل بها', max_length=255)),
                ('techs_title_en', models.CharField(default='Technologies We Use', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='techs/')),
                ('name_ar', models.CharField(max_length=100)),
                ('name_en', models.CharField(max_length=100)),
                ('desc_ar', models.CharField(max_length=255)),
                ('desc_en', models.CharField(max_length=255)),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technologies', to='website.aboutus')),
            ],
        ),
    ]
