# Generated by Django 5.2.4 on 2025-07-09 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_alter_service_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='color',
            field=models.CharField(default='#f8f9fa', max_length=20, verbose_name='لون خلفية الباقة'),
        ),
        migrations.AddField(
            model_name='package',
            name='description',
            field=models.TextField(default='سشغثي', verbose_name='وصف الباقة'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='package',
            name='description_ar',
            field=models.TextField(null=True, verbose_name='وصف الباقة'),
        ),
        migrations.AddField(
            model_name='package',
            name='description_en',
            field=models.TextField(null=True, verbose_name='وصف الباقة'),
        ),
        migrations.AddField(
            model_name='package',
            name='old_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='السعر قبل الخصم'),
        ),
        migrations.AlterField(
            model_name='package',
            name='category',
            field=models.CharField(choices=[('web', 'تصميم المواقع'), ('app', 'تطبيقات ومواقع'), ('hosting', 'الاستضافة والتسويق')], max_length=20, verbose_name='القسم'),
        ),
        migrations.AlterField(
            model_name='package',
            name='features',
            field=models.TextField(verbose_name='مميزات الباقة (افصل كل ميزة بسطر)'),
        ),
        migrations.AlterField(
            model_name='package',
            name='features_ar',
            field=models.TextField(null=True, verbose_name='مميزات الباقة (افصل كل ميزة بسطر)'),
        ),
        migrations.AlterField(
            model_name='package',
            name='features_en',
            field=models.TextField(null=True, verbose_name='مميزات الباقة (افصل كل ميزة بسطر)'),
        ),
        migrations.AlterField(
            model_name='package',
            name='name',
            field=models.CharField(max_length=200, verbose_name='عنوان الباقة'),
        ),
        migrations.AlterField(
            model_name='package',
            name='name_ar',
            field=models.CharField(max_length=200, null=True, verbose_name='عنوان الباقة'),
        ),
        migrations.AlterField(
            model_name='package',
            name='name_en',
            field=models.CharField(max_length=200, null=True, verbose_name='عنوان الباقة'),
        ),
        migrations.AlterField(
            model_name='package',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='السعر الحالي'),
        ),
    ]
