# Generated by Django 5.2.4 on 2025-07-09 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_package_color_package_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='color',
            field=models.CharField(choices=[('#f8f9fa', 'رمادي فاتح'), ('#e0f7fa', 'أزرق سماوي'), ('#ffe0b2', 'برتقالي فاتح'), ('#e1bee7', 'بنفسجي فاتح'), ('#c8e6c9', 'أخضر فاتح'), ('#ffccbc', 'وردي فاتح'), ('#d1c4e9', 'بنفسجي رمادي'), ('#b2dfdb', 'تركواز فاتح'), ('#f0f4c3', 'أصفر زيتوني فاتح')], default='#f8f9fa', max_length=20, verbose_name='لون خلفية الباقة'),
        ),
    ]
